---
# Default config file for logger
version: 1
formatters:
  colorlog:
    (): 'colorlog.ColoredFormatter'
    format: "[%(asctime)s] [%(log_color)s%(levelname)s%(reset)s] \
            [%(bold_white)s%(name)s%(reset)s] \
            [%(thin_white)s%(funcName)s%(reset)s] \
            %(message_log_color)s%(message)s%(reset)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
    log_colors:
      DEBUG: cyan
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: light_red
    secondary_log_colors:
      message:
        DEBUG: thin_white
        INFO: white
        WARNING: white
        ERROR: yellow
        CRITICAL: yellow
handlers:
  console:
    class: logging.StreamHandler
    formatter: colorlog
loggers:
  '':
    level: INFO
    handlers: [console]
  uvicorn:
    propagate: true
disable_existing_loggers: false
...
