---
# This is sample file with switches credentials
# Set up valid login and password values and copy contents to 'secrets.yml'
# admin_profile is used for node switches
# user_profile is used for access switches
admin_profile:
  login: admin
  password: adminpassword
user_profile:
  login: user
  password: userpassword
gray_database:
  login: graydbuser
  password: graydbpassword
...
