---
# Default config file for logger
version: 1
formatters:
  colorlog:
    (): 'colorlog.ColoredFormatter'
    format: "[%(bold_white)s%(name)s%(reset)s|\
            %(log_color)s%(levelname)s%(reset)s] \
            %(thin_white)s%(funcName)s%(reset)s: \
            %(message_log_color)s%(message)s%(reset)s"
    log_colors:
      DEBUG: cyan
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: light_red
    secondary_log_colors:
      message:
        DEBUG: thin_white
        INFO: white
        WARNING: white
        ERROR: yellow
        CRITICAL: yellow
handlers:
  colour:
    class: logging.StreamHandler
    formatter: colorlog
loggers:
  '':
    level: INFO
    handlers: [colour]
disable_existing_loggers: false
...
