---
# This is sample file with switches credentials
# Set up valid login and password values and rename this file to 'secrets.yml'
# admin_profile is used for node switches
# user_profile is used for access switches
secrets:
  admin_profile:
    login: admin
    password: adminpassword
  user_profile:
    login: user
    password: userpassword
...
